### ISSUE TITLE
Validating list of rios in dicom_series show_image() fails

### ISSUE THREAD

**Issue by psvenmarker** [BwKodex/dicomimagetools#40]
Should check isinstance(roi, Roi), not isinstance(roi, list)

`if rois is not None and (not isinstance(rois, list) or not all([isinstance(roi, Roi) for roi in rois])):`
`      raise TypeError("Only list of SquareRoi instances are implemented for plotting")`

**Comment by BwKodex** [comment]
Thanks for the report! The bug has now been fixed and is included in the newest release (v24.2.1)
